# -*- coding: utf-8 -*-
"""MPS_Template_Renderer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4lY6W4yo1nxPDInIKHtNQyF08u25MP_
"""

import pandas as pd
from jinja2 import Environment, FileSystemLoader

dF = pd.read_excel('/content/MPS-Finalised data1.0.xlsx')

print(dF.columns)
dF.fillna('None', inplace=True)

fileLoader = FileSystemLoader('/')
env = Environment(loader=fileLoader)
env.globals.update(zip=zip, str=str)
template = env.get_template('/content/template_final - Copy.j2')

def getData(dF, ind):
  noOfSons = dF['No. of Sons'][ind]
  if noOfSons == 'None':
    noOfSons = 0
  else:
    noOfSons = int(noOfSons)
  noOfDaughters = dF['No.of Daughters'][ind]
  if noOfDaughters == 'None':
    noOfDaughters = 0
  else:
    noOfDaughters = int(noOfDaughters)
  
  data = {
      'te_name': str(dF['te_name'][ind]).strip(),
      'Gender': str(dF['te_gender'][ind]).strip(),
      'images': str('Images.jpg').strip(),
      'te_date': str(dF['Date of Birth'][ind]).replace('00:00:00', ''),
      'te_placeofbirth': str(dF['te_place'][ind]).strip(),
      'father': str(dF['te_father'][ind]).strip(),
      'mother': str(dF['te_mother'][ind]).strip(),
      'education': str(dF['te_edu'][ind]).strip(),
      'profession': str(dF['te_profession'][ind]).strip(),
      'address': str(dF['te_presadd'][ind]).strip(),
      'maritalStatus': str(dF['te_marital'][ind]).strip(),
      'DateOfMarriage': str(dF['Date of Marriage'][ind]).strip().replace('00:00:00', ''),
      'spouse': str(dF['te_spouse'][ind]).strip(),
      'noOfSons':noOfSons,
      'noOfDaughters': noOfDaughters,
      'state': str(dF['te_constituency'][ind]).split('(')[-1].replace(')', '').strip(),
      'te_party_name': str(dF['te_party'][ind]).strip(),
      'constituency': str(dF['te_constituency'][ind]).strip(),
      'constituencyPlace': str(dF['te_constituency'][ind]).split('(')[0].replace(')', '').strip(),
      'member': str(dF['Lok Sabha Experience'][ind].split(',')[-1])
  }
  return data

print(template.render(getData(dF, 1)).strip())